# Utiliza la imagen oficial de Node.js para construir el proyecto
FROM node:16 as build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias y los instala
COPY package*.json ./
RUN npm install

# Copia el resto del código fuente
COPY . .

# Construye la aplicación para producción
RUN npm run build

# Fase de producción: Utiliza Nginx para servir el contenido estático
FROM nginx:alpine

# Copia el contenido estático construido desde la fase anterior
COPY --from=build /app/build /usr/share/nginx/html


# Expone el puerto 80
EXPOSE 80

# Iniciar Nginx cuando el contenedor se lance
CMD ["nginx", "-g", "daemon off;"]
