# Utiliza la imagen oficial de Node.js como imagen base
FROM node:16

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de dependencias del proyecto al directorio de trabajo
COPY package*.json ./

# Instala las dependencias del proyecto
RUN rm -rf node_modules
RUN npm install

# Copia los archivos del proyecto al directorio de trabajo en el contenedor
COPY . .

# Expone el puerto que tu aplicación utilizará
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["node", "index.js"]
